### ISSUE TITLE
Unable to install the OSGI Client Jar

### ISSUE THREAD

**Issue by jpsmoura** [gpe-mw-training/osgi-labs#5]
jserrade-OSX:osgi-client jmoura$ pwd
/Users/jmoura/Desktop/RedHat/Training/OSGi/Labs/osgi-labs-0.2-exercise/1_Introduction/osgi-client
jserrade-OSX:osgi-client jmoura$ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building RedHat GPE Training :: OSGi :: Lab :: 1 :: Greeter Client 1.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.882 s
[INFO] Finished at: 2016-03-23T14:22:15+00:00
[INFO] Final Memory: 12M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project osgi-client: Could not resolve dependencies for project com.redhat.gpe.training:osgi-client:bundle:1.0: Failed to collect dependencies at com.redhat.gpe.training:osgi-service:jar:1.0: Failed to read artifact descriptor for com.redhat.gpe.training:osgi-service:jar:1.0: Failure to find com.redhat.gpe.training:osgi-lab-1-project:pom:1.0 in http://maven.repository.redhat.com/techpreview/all was cached in the local repository, resolution will not be reattempted until the update interval of jboss-ga-repository has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by honghuac** [comment]
Please post this in the training server forums.
